#!/bin/sh
##
# Run tests for detect_codename().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that detect_codename returns true
( detect_codename ); [ "$?" = 0 ] || exit 1

# Check codename (if defined)
if [ -n "$EXPECT_CODENAME" ]; then
	(	detect_codename || return 1
		test "$H_CODENAME" = "$EXPECT_CODENAME"
	); [ "$?" = 0 ] || exit 1
else
	log "$WARN" 'EXPECT_CODENAME unset ; not running tests'
fi


# Complete
exit 0
