#!/bin/sh
##
# Run tests for detect_distro().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that some distro is detected
( detect_distro; test -n "$H_DISTRO" ); [ "$?" = 0 ] && exit 0

# Check distro (if defined)
if [ -n "$EXPECT_DISTRO" ]; then
	detect_distro
	[ "$H_DISTRO" = "$EXPECT_DISTRO" ] || exit 1
else
	log "$WARN" 'EXPECTED_DISTRO unset ; not running tests'
fi


# Complete
exit 0
