#!/bin/sh
##
# Run tests for detect_release().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that some release is detected
( detect_release; test -n "$H_RELEASE" ); [ "$?" = 0 ] && exit 0


# Complete
exit 0
