#!/bin/sh
##
# Run tests for detect_kernel().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that some kernel is detected
( detect_kernel; test -n "$H_KERNEL" ); [ "$?" = 0 ] && exit 0


# Complete
exit 0
