#!/bin/sh
##
# Run tests for detect_arch().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that some arch is detected
( detect_arch; test -n "$H_ARCH" ); [ "$?" = 0 ] || exit 1

# Check arch (if defined)
if [ -n "$EXPECT_ARCH" ]; then
	(	detect_arch || return 1
		test "$H_ARCH" = "$EXPECT_ARCH"
	); [ "$?" = 0 ] || exit 1
else
	log "$WARN" 'EXPECT_ARCH unset ; not running tests'
fi


# Complete
exit 0
