#!/bin/sh
##
# Run tests for die().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Check that 'die' without exit status exits w/ status=1
( die 'dead' ) >/dev/null; [ "$?" = '1' ] || exit 1

# When an exit status was set
( die 7 'dead' ) >/dev/null; [ "$?" = '7' ] || exit 1
( die 8 'dead' ) >/dev/null; [ "$?" = '0' ] && exit 1

# Permit a zero status on early exit
( die 0 'dead' ) >/dev/null; [ "$?" = '0' ] || exit 1

# Verify the right message was sent to stdout
[ "$(die 'dead')" = '*** CRITICAL: dead ***' ] || exit 1
[ "$(die 'dead')" = '*** CRITICAL: beef ***' ] && exit 1


# Complete
exit 0
