#!/bin/sh
##
# Run tests for in_string().
##
#set -x

. "$TESTDIR/../lib/shell"


# Simple 'true' searches
in_string 'abc' 'anthuabcaeua' || return 1
in_string '12' 'anthu12caeua' || return 1
in_string '12' '88812888' || return 1

# Simple 'false' searches
in_string 'abc' 'anthuacaeua' && return 1
in_string '12' 'anthu1caeua' && return 1
in_string '12' '8881888' && return 1

# Variable substituted 'true' searches
needle='abc'; haystack='*!V^abc;'
in_string "$needle" "$haystack" || return 1

# Variable substituted 'false' searches
needle='abc'; haystack='*!V^ABC;'
in_string "$needle" "$haystack" && return 1


# Complete
return 0
