#!/bin/sh
##
# Run tests for is_codename().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Static-defined H_CODENAME (true)
(
	export H_CODENAME='buster';
	is_codename 'buster' 'catalina'
); [ "$?" = '0' ] || exit 1

# Static-defined H_CODENAME (false)
(
	export H_CODENAME='wiley';
	is_codename 'buster' 'catalina'
); [ "$?" = '1' ] || exit 1


# Complete
exit 0
