#!/bin/sh
##
# Run tests for is_distro().
##
#set -x

. "$TESTDIR/../lib/shell"


# Static-defined H_DISTRO (true)
(
	export H_DISTRO='Ubuntu';
	is_distro 'Debian' 'Ubuntu'
); [ "$?" = '0' ] || return 1

# Static-defined H_DISTRO (false)
(
	export H_DISTRO='FreeBSD';
	is_distro 'Debian' 'Ubuntu'
); [ "$?" = '1' ] || return 1


# Complete
return 0
