#!/bin/sh
##
# Run tests for is_distro().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Static-defined H_DISTRO (true)
(
	export H_DISTRO='ubuntu';
	is_distro 'debian' 'ubuntu'
); [ "$?" = '0' ] || exit 1

# Static-defined H_DISTRO (false)
(
	export H_DISTRO='freebsd';
	is_distro 'debian' 'ubuntu'
); [ "$?" = '1' ] || exit 1


# Complete
exit 0
