#!/bin/sh
##
# Run tests for is_int().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Simple 'true' searches
is_int '1' || exit 1
is_int '01' || exit 1
is_int '10' || exit 1
is_int '198721387427' || exit 1

# Simple 'false' searches
is_int 'a' && exit 1
is_int '1a' && exit 1
is_int 'a1' && exit 1
is_int '12346791x23456' && exit 1
is_int '12346791_23456' && exit 1


# Complete
exit 0
