#!/bin/sh
##
# Run tests for is_kernel().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Static-defined H_KERNEL (true)
(
	export H_KERNEL='Linux';
	is_kernel 'Linux' 'AIX'
); [ "$?" = '0' ] || exit 1

# Static-defined H_KERNEL (false)
(
	export H_KERNEL='FreeBSD';
	is_kernel 'Linux' 'AIX'
); [ "$?" = '1' ] || exit 1


# Complete
exit 0
