#!/bin/sh
##
# Run tests for starts_with().
##
#set -x

. "$TEST_DIR/../lib/shell"


# Some (valid) strings to test
starts_with 'abc' 'abcdef' || exit 1
starts_with 'abc' 'abc123' || exit 1
starts_with '123' '123def' || exit 1
starts_with '*U#' '*U#AB3' || exit 1
starts_with '!^*' '!^*&@!' || exit 1

# Some (invalid) strings to test
starts_with 'abc' 'acbdef' && exit 1
starts_with 'ab1' 'abc123' && exit 1
starts_with '123' '124def' && exit 1
starts_with '*U3' '*U#AB3' && exit 1
starts_with '!^*' '!-*&@!' && exit 1

# String in the middle of a string (invalid)
starts_with 'U3' '*U#U3AB3' && exit 1


# Complete
exit 0
