#!/bin/sh
##
# Run tests for die().
##
#set -x

. "$TESTDIR/../lib/shell"


# Check that 'die' without exit status exits w/ status=1
( die 'dead' ) >/dev/null; [ "$?" = '1' ] || return 1

# When an exit status was set
( die 7 'dead' ) >/dev/null; [ "$?" = '7' ] || return 1
( die 8 'dead' ) >/dev/null; [ "$?" = '0' ] && return 1

# Permit a zero status on early exit
( die 0 'dead' ) >/dev/null; [ "$?" = '0' ] || return 1

# Verify the right message was sent to stdout
[ "$(die 'dead')" = '*** CRITICAL: dead ***' ] || return 1
[ "$(die 'dead')" = '*** CRITICAL: beef ***' ] && return 1


# Complete
return 0
