#!/bin/sh
##
# Find and run test units on shell scripts
##

TESTDIR="$(dirname "$0")"; export TESTDIR

TESTS_FAILED='false'


main() {
	# Run tests
	run_tests 'var' 'Variable'
	run_tests 'fun' 'Function'

	# Print summary
	if [ "$TESTS_FFAILED" = 'true' ]; then
		printf '!!! One or more tests failed. !!!\n'
		return 1
	fi
	return 0
}


run_tests() {
	printf 'Running %s Tests...\n' "$2"

	for path in "$TESTDIR/shell_units/$1/"*; do
		file="$(basename "$path")"
		# Skip files starting with an underscore
		[ "$file" = "${file#_}" ] || continue

		# Run test unit
		printf '%15s:\t' "$file"
		if ! sh "$path"; then
			printf 'FAILED\n'
			TESTS_FFAILED='true'
		else
			printf 'Passed\n'
		fi
	done
}


main "$@"
