#!/bin/sh
##
# Run tests for is_true().
##
#set -x

. "$TESTDIR/../lib/shell"


# Non-zero is false
is_false 0 && return 1
is_false 2 || return 1

# Valid 'true' strings
is_false 'True' && return 1
is_false 'true' && return 1
is_false 'TrUe' && return 1

# Invalid 'true' strings
is_false 'tru' || return 1
is_false 'truee' || return 1

# Valid 'non-true' strings
is_false 'False' || return 1
is_false 'false' || return 1

# Other strings
is_false '' || return 1
is_false '_' || return 1


# Complete
return 0
