#!/bin/sh
##
# Run tests for [DEBUG, D, INFO, I, WARN, W, ERROR, E].
##
#set -x

. "$TEST_DIR/../lib/shell"

# Check expected variables have expected values
[ "$DEBUG" = 0 ] || exit 1
[ "$D" = 0 ] || exit 1
[ "$INFO" = 1 ] || exit 1
[ "$I" = 1 ] || exit 1
[ "$WARN" = 2 ] || exit 1
[ "$W" = 2 ] || exit 1
[ "$ERROR" = 3 ] || exit 1
[ "$E" = 3 ] || exit 1

# Verify values cannot be changed
( DEBUG=77 ) 2>/dev/null && exit 1
( D=77 ) 2>/dev/null && exit 1
( INFO=77 ) 2>/dev/null && exit 1
( I=77 ) 2>/dev/null && exit 1
( WARN=77 ) 2>/dev/null && exit 1
( W=77 ) 2>/dev/null && exit 1
( ERROR=77 ) 2>/dev/null && exit 1
( E=77 ) 2>/dev/null && exit 1


# Complete
exit 0
