#!/usr/bin/env python3
'''
Generate a documentation file from input "library" scripts.
'''
import os
import re
import subprocess
import sys


WORKSPACE = os.environ.get('WORKSPACE', './')
SHELL_LIB = '{}/lib/shell'.format(WORKSPACE)
SHELL_DOC = '{}/docs/helpers/shell.rst'.format(WORKSPACE)


if not os.path.exists(SHELL_LIB):
    print('{} not found in context: skipping'.format(SHELL_LIB))
    sys.exit(0)

with open(SHELL_DOC, 'w') as _out:

    # Header
    _out.write('Shell Helpers\n=============\n\n')

    # Constants
    _out.write('Constants\n---------\n\n')
    proc = subprocess.Popen(
            '. {}; export'.format(SHELL_LIB),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True)
    exports = proc.communicate()[0].decode('utf-8')
    with open(SHELL_LIB, 'r') as _in:
        lines = ''.join(_in.readlines())
    for m in re.findall(r'^#\s(.*?)$\n^readonly\s(.+)', lines, re.M):
        _out.write('**{}:**\n\n'.format(m[0]))
        for var in m[1].split():
            _out.write('- {}: {}\n'.format(
                var,
                re.search(r'\s{}\=\'(.+?)\''.format(var), exports).group(1)))
        _out.write('\n')

    # Functions
    with open(SHELL_LIB, 'r') as _in:
        builder = ''
        for line in _in.readlines():
            if '() {\n' in line:
                command = line.split()[0]
                _out.write('{}\n{}\n\n{}\n'.format(
                    command,
                    ''.join(['-' for _ in command]),
                    builder))
                continue
            if line.startswith('##'):
                continue
            elif line.startswith('#'):
                builder += line.strip('#')
                continue
            else:
                builder = ''
                continue
