name: CI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:  ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1091
        # https://github.com/koalaman/shellcheck/wiki/SC1091

  posix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: POSIX Shell Tests
        run: make test_shell

  #python:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Python Tests
  #      run: echo 'Python Tests... NOT RUN'
  #      #run: make test_py
