name: Python3 Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  py3-ubuntu-latest:
    name: py3 (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          sudo apt install -y python3-pytest
          make test_py3
